//Michael, below is an example of the data we get back from the API requested from our server

{
  "last_item" : null,
  "total_items": "1299",
  "first_item": null,
  "page_number": "1",
  "page_size": "4",
  "page_items": null,
  "search_time": "0.033",
  "page_count": "325",
  "events": {
    "event": [
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "GA",
        "postal_code": "30307",
        "going_count": null,
        "all_day": "0",
        "latitude": "33.7936870",
        "groups": null,
        "url": "http://atlanta.eventful.com/events/ballet-institute-atlanta-nutcracker-story-excer-/E0-001-096548121-5?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-096548121-5",
        "privacy": "1",
        "city_name": "Atlanta",
        "link_count": null,
        "longitude": "-84.3159910",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Georgia",
        "start_time": "2016-12-11 14:00:00",
        "tz_id": null,
        "description": " <p>Ballet Institute of Atlanta presents...<br> The Nutcracker - Story Excerpts for Children<p>Perfect for young audiences, this is a condensed, one-hour performance of the holiday classic experience. Children are invited post-performance to meet and greet with the dancers and choreographers. A personal holiday experience they are sure to remember.<p>When:<br> December 10, 2016 2:00 pm or 7:00pm<br> December 11, 2016 2:00pm<p>Where:<br> Druid Hills High School<br> 1798 Haygood Drive NE Atlanta GA 30307<p><br> About Ballet Institute of Atlanta: Ballet Institute of Atlanta is a new ballet company and Pre-professional dance training center located in midtown Atlanta. BIA&#39;s diverse curriculum is curated to offer premier-level training in classical ballet and contemporary dance, private coaching and cross-training for dancers ages 3-Adult. To find out more about Ballet Institute of Atlanta click www.balletinstituteofatlanta.com </p></p></p></p></p>",
        "modified": "2016-10-01 14:52:16",
        "venue_display": "1",
        "tz_country": null,
        "performers": {
          "performer": {
            "creator": "evdb",
            "linker": "evdb",
            "name": "The Nutcracker",
            "url": "http://eventful.com/performers/the-nutcracker-/P0-001-000249118-0?utm_source=apis&utm_medium=apim&utm_campaign=apic",
            "id": "P0-001-000249118-0",
            "short_bio": "The Nutcracker"
          }
        },
        "title": "Ballet Institute of Atlanta: The Nutcracker - Story Excerpts for Children",
        "venue_address": "1798 Haygood Drive",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": null,
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
          "small": {
            "width": "48",
            "url": "http://s1.evcdn.com/images/small/I0-001/005/497/444-2.jpeg_/the-nutcracker-44.jpeg",
            "height": "48"
          },
          "width": "48",
          "caption": null,
          "medium": {
            "width": "128",
            "url": "http://s1.evcdn.com/images/medium/I0-001/005/497/444-2.jpeg_/the-nutcracker-44.jpeg",
            "height": "128"
          },
          "url": "http://s1.evcdn.com/images/small/I0-001/005/497/444-2.jpeg_/the-nutcracker-44.jpeg",
          "thumb": {
            "width": "48",
            "url": "http://s1.evcdn.com/images/thumb/I0-001/005/497/444-2.jpeg_/the-nutcracker-44.jpeg",
            "height": "48"
          },
          "height": "48"
        },
        "created": "2016-09-17 08:57:22",
        "venue_id": "V0-001-000727591-2",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Druid Hills High School",
        "venue_url": "http://atlanta.eventful.com/venues/druid-hills-high-school-/V0-001-000727591-2?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "GA",
        "postal_code": "31088",
        "going_count": null,
        "all_day": "0",
        "latitude": "32.5790858",
        "groups": null,
        "url": "http://eventful.com/warnerrobins/events/irish-christmas-celebration-carols-keith-kri-/E0-001-095390926-8?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-095390926-8",
        "privacy": "1",
        "city_name": "Warner Robins",
        "link_count": null,
        "longitude": "-83.6238108",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Georgia",
        "start_time": "2016-12-11 19:30:00",
        "tz_id": null,
        "description": " Join Ireland’s own Keith and Kristyn Getty, writers of modern hymns and carols, for their fifth annual tour of Irish Christmas-A Celebration of Carols! As seen on Public Television, the Gettys are joined by their band of virtuoso instrumentalists fusing Celtic, Bluegrass, Americana, and classical music as well as cultural dance and the choral sounds of the holiday. Come sing along with Keith and Kristyn and their special guest friends on an evening that unites tradition and innovation in a vibrant celebration of the season! Note: Childcare will not be provided.  ",
        "modified": "2016-12-07 20:06:25",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "Irish Christmas - A Celebration of Carols (with Keith & Kristyn Getty)",
        "venue_address": "2504 Moody Road",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": null,
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
          "small": {
            "width": "48",
            "url": "http://s2.evcdn.com/images/small/I0-001/035/832/137-5.jpeg_/irish-christmas-celebration-carols-keith-kristyn-37.jpeg",
            "height": "48"
          },
          "width": "48",
          "caption": null,
          "medium": {
            "width": "128",
            "url": "http://s2.evcdn.com/images/medium/I0-001/035/832/137-5.jpeg_/irish-christmas-celebration-carols-keith-kristyn-37.jpeg",
            "height": "128"
          },
          "url": "http://s2.evcdn.com/images/small/I0-001/035/832/137-5.jpeg_/irish-christmas-celebration-carols-keith-kristyn-37.jpeg",
          "thumb": {
            "width": "48",
            "url": "http://s2.evcdn.com/images/thumb/I0-001/035/832/137-5.jpeg_/irish-christmas-celebration-carols-keith-kristyn-37.jpeg",
            "height": "48"
          },
          "height": "48"
        },
        "created": "2016-08-01 09:54:48",
        "venue_id": "V0-001-005400819-2",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Second Baptist Warner Robbins",
        "venue_url": "http://eventful.com/warnerrobins/venues/second-baptist-warner-robbins-/V0-001-005400819-2?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "GA",
        "postal_code": null,
        "going_count": null,
        "all_day": "0",
        "latitude": "33.9134490",
        "groups": null,
        "url": "http://atlanta.eventful.com/events/breakfast-santa-maggianos-2016-/E0-001-097829420-2?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-097829420-2",
        "privacy": "1",
        "city_name": "Atlanta",
        "link_count": null,
        "longitude": "-84.3420840",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Georgia",
        "start_time": "2016-12-11 08:00:00",
        "tz_id": null,
        "description": " Come visit with Santa and Mrs. Claus at Maggiano&#39;s - Perimeter Mall   We have TWO dates to experience the Magic! Sunday, December 11th, 2016 AND Sunday, December 18th, 2016 From 8 AM - 10 AM  Your child will not only enjoy time with Santa, but also have a chance to tell Santa what they want for Christmas.  You will also have the opportunity to take their picture. (Parents, please remember your cameras!)  Maggiano&#39;s will feature a delicious breakfast buffet and hot cocoa station.  Children will enjoy decorating cookies and making their own &quot;magic reindeer food&quot; in the hopes that Santa and his reindeer will visit on Christmas Eve. ",
        "modified": "2016-11-14 03:14:11",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "Breakfast with Santa at Maggiano's 2016",
        "venue_address": "4000 Summit Boulevard",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": null,
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
          "small": {
            "width": "48",
            "url": "http://s3.evcdn.com/images/small/I0-001/034/941/558-4.x-ms-bmp",
            "height": "48"
          },
          "width": "48",
          "caption": null,
          "medium": {
            "width": "128",
            "url": "http://s3.evcdn.com/images/medium/I0-001/034/941/558-4.x-ms-bmp",
            "height": "128"
          },
          "url": "http://s3.evcdn.com/images/small/I0-001/034/941/558-4.x-ms-bmp",
          "thumb": {
            "width": "48",
            "url": "http://s3.evcdn.com/images/thumb/I0-001/034/941/558-4.x-ms-bmp",
            "height": "48"
          },
          "height": "48"
        },
        "created": "2016-11-14 03:14:11",
        "venue_id": "V0-001-000216149-2",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Villa Christina",
        "venue_url": "http://atlanta.eventful.com/venues/villa-christina-/V0-001-000216149-2?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "GA",
        "postal_code": "30319",
        "going_count": null,
        "all_day": "0",
        "latitude": "33.9322433",
        "groups": null,
        "url": "http://atlanta.eventful.com/events/swingin-holidays-brent-runnels-trio-/E0-001-097721571-2?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-097721571-2",
        "privacy": "1",
        "city_name": "Atlanta",
        "link_count": null,
        "longitude": "-84.2684986",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Georgia",
        "start_time": "2016-12-11 16:00:00",
        "tz_id": null,
        "description": "Join The Brent Runnels Trio for a festive afternoon of music in the Oglethorpe University Museum of Art! \n\nThe Brent Runnels Trio features Brent Runnels on piano, Ben Bailey on drums and Kevin Smith on Bass.",
        "modified": "2016-11-10 07:40:32",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "Swingin’ in the Holidays with The Brent Runnels Trio",
        "venue_address": "4484 Peachtree Road N Rd",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": null,
        "calendars": null,
        "owner": "rvaryb254f",
        "going": null,
        "country_abbr2": "US",
        "image": {
          "small": {
            "width": "48",
            "url": "http://s4.evcdn.com/images/small/I0-001/034/791/679-7.jpeg_/swingin-holidays-brent-runnels-trio-79.jpeg",
            "height": "48"
          },
          "width": "48",
          "caption": null,
          "medium": {
            "width": "128",
            "url": "http://s4.evcdn.com/images/medium/I0-001/034/791/679-7.jpeg_/swingin-holidays-brent-runnels-trio-79.jpeg",
            "height": "128"
          },
          "url": "http://s4.evcdn.com/images/small/I0-001/034/791/679-7.jpeg_/swingin-holidays-brent-runnels-trio-79.jpeg",
          "thumb": {
            "width": "48",
            "url": "http://s4.evcdn.com/images/thumb/I0-001/034/791/679-7.jpeg_/swingin-holidays-brent-runnels-trio-79.jpeg",
            "height": "48"
          },
          "height": "48"
        },
        "created": "2016-11-10 07:40:32",
        "venue_id": "V0-001-000183192-9",
        "tz_city": null,
        "stop_time": "2016-12-11 17:00:00",
        "venue_name": "Oglethorpe University Museum of Art",
        "venue_url": "http://atlanta.eventful.com/venues/oglethorpe-university-museum-of-art-/V0-001-000183192-9?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      }
    ]
  }
}